language: python

python:
  - "3.6"

env:
  - DJANGO_VERSION=1.10.5

install:
  - pip install -r requirements.txt

script:
  - python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API