language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  # PyPy - deployment version
  - "pypy"
env:
  - DJANGO_VERSION=1.10.5

install:
  - pip install -q Django==$DJANGO_VERSION

script:
  - python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API