# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
                ('height', models.DecimalField(decimal_places=2, default=4.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('height', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], default='left', max_length=16)),
                ('style', models.CharField(max_length=255)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardType')),
            ],
        ),
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='cardtype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Project'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardType'),
        ),
    ]
