# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='height',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Distance from top, percentage'),
        ),
        migrations.AlterField(
            model_name='field',
            name='style',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='field',
            name='width',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5, verbose_name='Width, percentage'),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cards.Field'),
        ),
    ]
