# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
