# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_field_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='is_italic',
            field=models.BooleanField(default=False),
        ),
    ]
