# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20170217_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card'),
        ),
    ]
