# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20170227_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='font_size',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=3, verbose_name='Font-size, percentage'),
        ),
    ]
